/* This file is generated by SAPCC. Edits may be lost. */
#ifndef _CALC_AST_H
#define _CALC_AST_H

#include "util.h"

typedef enum {
    AST_NTERM,
    AST_TERM,
} AstType;

typedef struct {
    uint16_t type;
    List* attr_list;
} Ast;

typedef struct {
    AstType type;
    void* value;
} AstEntry;

Ast* create_ast_node(uint16_t type, List* lst);
void add_ast_attr(Ast* ast, AstEntry* attr);


#endif

