/* This file is generated by SAPCC. Edits may be lost. */
#include "util.h"

#include "calc_ast.h"

Ast* create_ast_node(uint16_t type, List* lst) {

    Ast* ptr = _ALLOC_T(Ast);
    ptr->type = type;
    ptr->attr_list = lst;

    return ptr;
}

void add_ast_attr(Ast* ast, AstEntry* attr) {
    append_list(ast->attr_list, (void*)attr);
}

