
#include "parser.h"
#include "emitters.h"
#include "paths.h"
#include "logger.h"

#define ELEVEL 10

typedef struct {
    Str* base;
    Parser* pstate;
} Emitters;

static Emitters* emitters;

static void opening(FILE* fp) {

    fprintf(fp, "/* This file is generated by SAPCC. Edits may be lost. */\n");
}

static void header_post(FILE* fp) {

    fprintf(fp, "\n#endif\n\n");
    fclose(fp);
}

static FILE* header_pre(const char* name) {

    char buffer[1024];
    char* p;

    strncpy(buffer, raw_string(emitters->base), 10);
    strncat(buffer, name, 1000);
    if(NULL == (p = strrchr(buffer, '.')))
        strcat(buffer, ".h");

    FILE* fp = fopen(buffer, "w");

    p = strrchr(buffer, '.');
        *p = '_';

    opening(fp);
    for(p = buffer; *p != '\0'; p++)
        *p = toupper(*p);

    fprintf(fp, "#ifndef _%s\n", buffer);
    fprintf(fp, "#define _%s\n\n", buffer);
    return fp;
}

static void source_post(FILE* fp) {

    fclose(fp);
}

static FILE* source_pre(const char* name) {

    char buffer[1024];
    char* p;

    strncpy(buffer, raw_string(emitters->base), 10);
    strncat(buffer, name, 1000);
    if(NULL == (p = strrchr(buffer, '.')))
        strcat(buffer, ".c");

    FILE* fp = fopen(buffer, "w");
    opening(fp);
    fprintf(fp, "#include \"util.h\"\n\n");
    return fp;
}



void init_emitters(Parser* pstate) {

    emitters = _ALLOC_T(Emitters);
    emitters->pstate = pstate;

    TRY {
        emitters->base = get_cmd_str(cmd, "ofile");
    }
    EXCEPT(LIST_ERROR) {
        emitters->base = get_cmd_str(cmd, "file");
        emitters->base = path_basename(emitters->base);
        emitters->base = path_stripext(emitters->base);
    }
    FINAL

    LOG(ELEVEL, "using the output name: %s\n", raw_string(emitters->base));
}

void emit_scanner_h() {

    FILE* fp = header_pre("_scanner");

    Terminal* term;
    TermListIter* tli = init_list_iterator(emitters->pstate->terminals);
    fprintf(fp, "typedef enum {\n");
    while(iterate_list(tli, &term))
        fprintf(fp, "    %s = %d,\n", raw_string(term->name), term->val);
    fprintf(fp, "} TokenType;\n\n");

    fprintf(fp, "typedef struct {\n");
    fprintf(fp, "    Str* str;\n");
    fprintf(fp, "    TokenType type;\n");
    fprintf(fp, "} Token;\n\n");

    fprintf(fp, "extern Token token;\n\n");

    fprintf(fp, "Token* create_token();\n");
    fprintf(fp, "void open_file(const char* fname);\n");
    fprintf(fp, "Token* get_token();\n");
    fprintf(fp, "void consume_token();\n");
    fprintf(fp, "const char* tok_to_str(TokenType type);\n\n");

    header_post(fp);
}

void emit_parser_c() {

    FILE* fp = source_pre("_parser");
    source_post(fp);
}

void emit_parser_h() {

    FILE* fp = header_pre("_parser");
    header_post(fp);
}

void emit_ast_c() {

    FILE* fp = source_pre("_ast");
    source_post(fp);
}

void emit_ast_h() {

    FILE* fp = header_pre("_ast");
    header_post(fp);
}

void emit_visitor_c() {

    FILE* fp = source_pre("_visitor");
    source_post(fp);
}

void emit_visitor_h() {

    FILE* fp = header_pre("_visitor");
    header_post(fp);
}

void emit_all(Parser* pstate) {

    init_emitters(pstate);
    emit_scanner_h();
    emit_parser_c();
    emit_parser_h();
    emit_ast_c();
    emit_ast_h();
    emit_visitor_c();
    emit_visitor_h();
}
